<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Student;
use App\Models\SchoolClass;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // الحصول على جميع الفصول
        $classes = SchoolClass::all();
        
        // بيانات الطلاب
        $students = [
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00001',
                'full_name' => 'أحمد محمد عبدالله',
                'national_id' => '1234567890',
                'birth_date' => '2005-03-15',
                'gender' => 'male',
                'nationality' => 'سعودي',
                'phone' => '0501234567',
                'email' => 'ahmed.student@example.com',
                'guardian_name' => 'محمد عبدالله',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0507654321',
                'guardian_email' => 'mohamed.father@example.com',
                'enrollment_date' => '2021-09-01',
                'status' => 'active',
                'notes' => 'طالب متفوق في الرياضيات',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00002',
                'full_name' => 'فاطمة خالد العتيبي',
                'national_id' => '2345678901',
                'birth_date' => '2006-07-22',
                'gender' => 'female',
                'nationality' => 'سعودية',
                'phone' => '0552345678',
                'email' => 'fatima.student@example.com',
                'guardian_name' => 'خالد العتيبي',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0558765432',
                'guardian_email' => 'khaled.father@example.com',
                'enrollment_date' => '2022-09-01',
                'status' => 'active',
                'notes' => 'طالبة نشطة في الأنشطة المدرسية',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00003',
                'full_name' => 'عبدالله سالم الغامدي',
                'national_id' => '3456789012',
                'birth_date' => '2005-11-08',
                'gender' => 'male',
                'nationality' => 'سعودي',
                'phone' => '0533456789',
                'email' => 'abdullah.student@example.com',
                'guardian_name' => 'سالم الغامدي',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0539876543',
                'guardian_email' => 'salem.father@example.com',
                'enrollment_date' => '2021-09-01',
                'status' => 'active',
                'notes' => 'طالب يهتم بالبرمجة',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00004',
                'full_name' => 'نورة إبراهيم الشهري',
                'national_id' => '4567890123',
                'birth_date' => '2006-02-14',
                'gender' => 'female',
                'nationality' => 'سعودية',
                'phone' => '0544567890',
                'email' => 'nora.student@example.com',
                'guardian_name' => 'إبراهيم الشهري',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0540987654',
                'guardian_email' => 'ibrahim.father@example.com',
                'enrollment_date' => '2022-09-01',
                'status' => 'active',
                'notes' => 'طالبة متفوقة في اللغة العربية',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00005',
                'full_name' => 'سعد محمد الزهراني',
                'national_id' => '5678901234',
                'birth_date' => '2005-09-30',
                'gender' => 'male',
                'nationality' => 'سعودي',
                'phone' => '0565678901',
                'email' => 'saad.student@example.com',
                'guardian_name' => 'محمد الزهراني',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0561098765',
                'guardian_email' => 'mohamed.zahrani@example.com',
                'enrollment_date' => '2021-09-01',
                'status' => 'active',
                'notes' => 'طالب ممتاز في العلوم',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00006',
                'full_name' => 'مريم عبدالعزيز القحطاني',
                'national_id' => '6789012345',
                'birth_date' => '2006-05-18',
                'gender' => 'female',
                'nationality' => 'سعودية',
                'phone' => '0576789012',
                'email' => 'mariam.student@example.com',
                'guardian_name' => 'عبدالعزيز القحطاني',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0572109876',
                'guardian_email' => 'abdulaziz.qahtani@example.com',
                'enrollment_date' => '2022-09-01',
                'status' => 'active',
                'notes' => 'طالبة نشطة في الفنون',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00007',
                'full_name' => 'خالد سعيد الحربي',
                'national_id' => '7890123456',
                'birth_date' => '2005-12-25',
                'gender' => 'male',
                'nationality' => 'سعودي',
                'phone' => '0587890123',
                'email' => 'khaled.student@example.com',
                'guardian_name' => 'سعيد الحربي',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0583210987',
                'guardian_email' => 'saeed.harbi@example.com',
                'enrollment_date' => '2021-09-01',
                'status' => 'active',
                'notes' => 'طالب رياضي ممتاز',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00008',
                'full_name' => 'هناء يوسف العنزي',
                'national_id' => '8901234567',
                'birth_date' => '2006-04-10',
                'gender' => 'female',
                'nationality' => 'سعودية',
                'phone' => '0598901234',
                'email' => 'hana.student@example.com',
                'guardian_name' => 'يوسف العنزي',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0594321098',
                'guardian_email' => 'yousef.anazi@example.com',
                'enrollment_date' => '2022-09-01',
                'status' => 'active',
                'notes' => 'طالبة مهتمة بالأدب',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00009',
                'full_name' => 'عبدالرحمن فهد الدوسري',
                'national_id' => '9012345678',
                'birth_date' => '2005-08-05',
                'gender' => 'male',
                'nationality' => 'سعودي',
                'phone' => '0519012345',
                'email' => 'abdulrahman.student@example.com',
                'guardian_name' => 'فهد الدوسري',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0515432109',
                'guardian_email' => 'fahad.dosari@example.com',
                'enrollment_date' => '2021-09-01',
                'status' => 'active',
                'notes' => 'طالب متفوق في الكيمياء',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00010',
                'full_name' => 'صفية عمر الشمري',
                'national_id' => '0123456789',
                'birth_date' => '2006-06-20',
                'gender' => 'female',
                'nationality' => 'سعودية',
                'phone' => '0520123456',
                'email' => 'safiya.student@example.com',
                'guardian_name' => 'عمر الشمري',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0526543210',
                'guardian_email' => 'omar.shamari@example.com',
                'enrollment_date' => '2022-09-01',
                'status' => 'active',
                'notes' => 'طالبة متفوقة في الفيزياء',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00011',
                'full_name' => 'ناصر بدر العسيري',
                'national_id' => '1234509876',
                'birth_date' => '2005-10-15',
                'gender' => 'male',
                'nationality' => 'سعودي',
                'phone' => '0531234509',
                'email' => 'nasser.student@example.com',
                'guardian_name' => 'بدر العسيري',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0537654321',
                'guardian_email' => 'badr.aseeri@example.com',
                'enrollment_date' => '2021-09-01',
                'status' => 'active',
                'notes' => 'طالب يهتم بالتاريخ',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00012',
                'full_name' => 'ليلى سعد المري',
                'national_id' => '2345610987',
                'birth_date' => '2006-03-25',
                'gender' => 'female',
                'nationality' => 'سعودية',
                'phone' => '0542345610',
                'email' => 'laila.student@example.com',
                'guardian_name' => 'سعد المري',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0548765432',
                'guardian_email' => 'saad.mari@example.com',
                'enrollment_date' => '2022-09-01',
                'status' => 'active',
                'notes' => 'طالبة مهتمة بالفنون الجميلة',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00013',
                'full_name' => 'أحمد صالح البقمي',
                'national_id' => '3456721098',
                'birth_date' => '2005-07-12',
                'gender' => 'male',
                'nationality' => 'سعودي',
                'phone' => '0553456721',
                'email' => 'ahmed.baqmi@example.com',
                'guardian_name' => 'صالح البقمي',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0559876543',
                'guardian_email' => 'saleh.baqmi@example.com',
                'enrollment_date' => '2021-09-01',
                'status' => 'active',
                'notes' => 'طالب متفوق في الرياضيات',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00014',
                'full_name' => 'نورة عبدالله الحماد',
                'national_id' => '4567832109',
                'birth_date' => '2006-01-08',
                'gender' => 'female',
                'nationality' => 'سعودية',
                'phone' => '0564567832',
                'email' => 'nora.hamad@example.com',
                'guardian_name' => 'عبدالله الحماد',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0561098765',
                'guardian_email' => 'abdullah.hamad@example.com',
                'enrollment_date' => '2022-09-01',
                'status' => 'active',
                'notes' => 'طالبة مهتمة بالعلوم',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00015',
                'full_name' => 'سالم عواد الشمراني',
                'national_id' => '5678943210',
                'birth_date' => '2005-06-30',
                'gender' => 'male',
                'nationality' => 'سعودي',
                'phone' => '0575678943',
                'email' => 'salem.shamrani@example.com',
                'guardian_name' => 'عواد الشمراني',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0572109876',
                'guardian_email' => 'awad.shamrani@example.com',
                'enrollment_date' => '2021-09-01',
                'status' => 'active',
                'notes' => 'طالب متفوق في اللغة الإنجليزية',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00016',
                'full_name' => 'أمل سالم المطيري',
                'national_id' => '6789054321',
                'birth_date' => '2006-09-18',
                'gender' => 'female',
                'nationality' => 'سعودية',
                'phone' => '0586789054',
                'email' => 'amal.mutairi@example.com',
                'guardian_name' => 'سالم المطيري',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0583210987',
                'guardian_email' => 'salem.mutairi@example.com',
                'enrollment_date' => '2022-09-01',
                'status' => 'active',
                'notes' => 'طالبة نشطة في الأنشطة الاجتماعية',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00017',
                'full_name' => 'فيصل تركي الرويلي',
                'national_id' => '7890165432',
                'birth_date' => '2005-04-22',
                'gender' => 'male',
                'nationality' => 'سعودي',
                'phone' => '0597890165',
                'email' => 'faisal.rowaili@example.com',
                'guardian_name' => 'تركي الرويلي',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0594321098',
                'guardian_email' => 'turki.rowaili@example.com',
                'enrollment_date' => '2021-09-01',
                'status' => 'active',
                'notes' => 'طالب مهتم بكرة القدم',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00018',
                'full_name' => 'خديجة راشد السبيعي',
                'national_id' => '8901276543',
                'birth_date' => '2006-11-05',
                'gender' => 'female',
                'nationality' => 'سعودية',
                'phone' => '0518901276',
                'email' => 'khadija.subaie@example.com',
                'guardian_name' => 'راشد السبيعي',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0515432109',
                'guardian_email' => 'rashed.subaie@example.com',
                'enrollment_date' => '2022-09-01',
                'status' => 'active',
                'notes' => 'طالبة متفوقة في الرياضيات',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00019',
                'full_name' => 'عبدالله فيصل العتيبي',
                'national_id' => '9012387654',
                'birth_date' => '2005-02-14',
                'gender' => 'male',
                'nationality' => 'سعودي',
                'phone' => '0529012387',
                'email' => 'abdullah.oteibi@example.com',
                'guardian_name' => 'فيصل العتيبي',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0526543210',
                'guardian_email' => 'faisal.oteibi@example.com',
                'enrollment_date' => '2021-09-01',
                'status' => 'active',
                'notes' => 'طالب متفوق في العلوم',
            ],
            [
                'class_id' => $classes->random()->id,
                'student_id' => 'STU-00020',
                'full_name' => 'مها خالد الحربي',
                'national_id' => '0123498765',
                'birth_date' => '2006-07-28',
                'gender' => 'female',
                'nationality' => 'سعودية',
                'phone' => '0530123498',
                'email' => 'maha.harbi@example.com',
                'guardian_name' => 'خالد الحربي',
                'guardian_relation' => 'الأب',
                'guardian_phone' => '0537654321',
                'guardian_email' => 'khaled.harbi@example.com',
                'enrollment_date' => '2022-09-01',
                'status' => 'active',
                'notes' => 'طالبة مهتمة بالأدب والشعر',
            ],
        ];
        
        // إدخال بيانات الطلاب في قاعدة البيانات
        foreach ($students as $student) {
            Student::create($student);
        }
    }
}
